import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const packagesDir = join(import.meta.dirname, '..', 'packages');
const readmePath = join(import.meta.dirname, '..', 'README.md');
const repo = 'https://github.com/auron-labs/opencode-plugins';

interface PackageInfo {
  name: string;
  description: string;
  dir: string;
}

const packages: PackageInfo[] = [];

for (const entry of readdirSync(packagesDir, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const pkgJsonPath = join(packagesDir, entry.name, 'package.json');
  try {
    const pkg = JSON.parse(readFileSync(pkgJsonPath, 'utf-8'));
    if (pkg.name && pkg.description) {
      packages.push({ name: pkg.name, description: pkg.description, dir: entry.name });
    }
  } catch {
    // ponytail: skip dirs without package.json
  }
}

packages.sort((a, b) => a.name.localeCompare(b.name));

let readme = '<!-- generated by bun run readme; do not edit by hand -->\n\n';
readme += '# opencode-plugins\n\n';
readme += '[![License](https://img.shields.io/github/license/auron-labs/opencode-plugins?style=flat-square)](./LICENSE) ';
readme += `[![CI](https://img.shields.io/github/actions/workflow/status/auron-labs/opencode-plugins/ci.yaml?branch=main&style=flat-square&label=ci)](${repo}/actions/workflows/ci.yaml) `;
readme += `[![Release](https://img.shields.io/github/actions/workflow/status/auron-labs/opencode-plugins/release.yaml?branch=main&style=flat-square&label=release)](${repo}/actions/workflows/release.yaml)\n\n`;
readme += 'OpenCode plugin workspace with small, focused packages for codebase indexing, audit planning, provider auth, and terminal automation.\n\n';
readme += '## Packages\n\n';
readme += '| Package | Use it for | Install |\n';
readme += '| --- | --- | --- |\n';

for (const pkg of packages) {
  readme += `| [${pkg.name}](./packages/${pkg.dir}) | ${pkg.description} | \`bun add ${pkg.name}\` |\n`;
}

readme += '\n';
readme += 'Each package is published to npm and can also be installed with `npm install <package>` if you are not using Bun.\n\n';
readme += 'Some plugins also expect local tools on `PATH`:\n\n';
readme += '- `@auron-labs/opencode-codebase-memory` expects `codebase-memory-mcp` unless you configure a custom binary path.\n';
readme += '- `@auron-labs/opencode-zellij` expects a running Zellij session and the `zellij` binary.\n\n';
readme += '## Quick Start\n\n';
readme += 'Install the plugin you want, add it to your OpenCode config, then restart OpenCode.\n\n';
readme += '```bash\n';
readme += 'bun add @auron-labs/opencode-codebase-memory\n';
readme += '```\n\n';
readme += '```json\n';
readme += '{\n';
readme += '  "plugin": [\n';
readme += '    ["@auron-labs/opencode-codebase-memory", {}],\n';
readme += '    ["@auron-labs/opencode-improve", {}]\n';
readme += '  ]\n';
readme += '}\n';
readme += '```\n\n';
readme += 'Package-specific configuration, requirements, and examples live in each package README:\n\n';

for (const pkg of packages) {
  readme += `- [${pkg.name}](./packages/${pkg.dir})\n`;
}

readme += '\n';
readme += '## Troubleshooting\n\n';
readme += '- Restart OpenCode after changing plugin configuration.\n';
readme += '- Check the package README for required local binaries and runtime prerequisites.\n';
readme += '- When developing locally, run `bun run build` before linking or testing unpublished package changes.\n\n';
readme += '## Development\n\n';
readme += '```bash\n';
readme += 'mise install\n';
readme += 'bun install --frozen-lockfile\n';
readme += 'mise run lint\n';
readme += 'bun run build\n';
readme += 'bun run test\n';
readme += 'mise run check\n';
readme += 'bun run readme\n';
readme += 'bunx release-please manifest-pr --config-file release-please-config.json --manifest-file .release-please-manifest.json --target-branch main\n';
readme += '```\n';

writeFileSync(readmePath, readme);
